"""Draft Word Tool — generate a formatted .docx approval note from extracted data."""
import sys
import os
import tempfile
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from config import OUTPUT_DIR


async def run_draft_word(
    extracted_data: dict,
    document_type: str = "approval_note",
    title: str = "Inspection Report — Approval Note",
) -> dict:
    """
    Generate a professional Word document (.docx) from extracted data.

    Args:
        extracted_data: Dict with keys: summary, findings, risks, recommendations
        document_type:  Document template type (currently: "approval_note")
        title:          Document title string

    Returns:
        {
            "success": bool,
            "file_path": str,   -- absolute path to .docx
            "filename": str,
            "error": str|None
        }
    """
    try:
        doc = Document()
        _set_base_style(doc)

        # ── Title / Header ──
        heading = doc.add_heading(title, level=1)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Date line
        date_para = doc.add_paragraph(
            f"Date: {datetime.now().strftime('%d %B %Y')}"
        )
        date_para.runs[0].italic = True
        date_para.runs[0].font.color.rgb = RGBColor(0x44, 0x44, 0x44)

        doc.add_paragraph()  # spacer

        # ── Executive Summary ──
        doc.add_heading("Executive Summary", level=2)
        summary = extracted_data.get("summary", "No summary available.")
        doc.add_paragraph(summary)
        doc.add_paragraph()

        # ── Key Findings ──
        findings = extracted_data.get("findings", [])
        if findings:
            doc.add_heading("Key Findings", level=2)
            for finding in findings:
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(str(finding))
            doc.add_paragraph()

        # ── Identified Risks ──
        risks = extracted_data.get("risks", [])
        if risks:
            doc.add_heading("Identified Risks", level=2)
            for risk in risks:
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(str(risk))
                run.font.color.rgb = RGBColor(0xC0, 0x00, 0x00)
            doc.add_paragraph()

        # ── Recommendations ──
        recs = extracted_data.get("recommendations", [])
        if recs:
            doc.add_heading("Recommendations", level=2)
            for rec in recs:
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(str(rec))
            doc.add_paragraph()

        # ── Approval Section ──
        doc.add_heading("Approval", level=2)
        doc.add_paragraph("Status:  ☐ Approved       ☐ Rejected       ☐ Pending Review")
        doc.add_paragraph()
        doc.add_paragraph("Authorized Signatory: ___________________________")
        doc.add_paragraph("Designation:          ___________________________")
        doc.add_paragraph("Date:                 ___________________________")
        doc.add_paragraph()

        # ── Footer ──
        footer_p = doc.add_paragraph(
            "Generated by SovereignForge — Sovereign On-Premise AI Workbench"
        )
        footer_run = footer_p.runs[0]
        footer_run.font.size = Pt(8)
        footer_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
        footer_run.italic = True

        # ── Save ──
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{document_type}_{timestamp}.docx"
        file_path = os.path.join(OUTPUT_DIR, filename)
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        doc.save(file_path)

        return {
            "success": True,
            "file_path": file_path,
            "filename": filename,
            "error": None,
        }

    except Exception as exc:
        return {
            "success": False,
            "file_path": "",
            "filename": "",
            "error": str(exc),
        }


def _set_base_style(doc: Document) -> None:
    """Apply base typography to the document."""
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
